feat: amend kms policy for encryption
Ensono/stacks-terraform pull request #122
Opened 2024-06-05 10:05 UTC by dibyadhar

#### 📲 What

Update kms encryption policy to pass IAM Role so that we can deploy using cross-account role in higher environments.

#### 🤔 Why

When using cross account IAM role for terraform planning the cluster it fails as the deployer role didn't have access to the kms keys

#### 🛠 How

conditionally injecting via terraform variables

#### 👀 Evidence

![image](https://github.com/Ensono/stacks-terraform/assets/65091252/65e92faf-5514-4528-bc74-7b232023b7db)

#### 🕵️ How to test

After updating the policy we need to run the plan for infrastructure code with cross account IAM role.

#### ✅ Acceptance criteria Checklist

- [ ] Code peer reviewed?
- [ ] Documentation has been updated to reflect the changes?
- [ ] Passing all automated tests, including a successful deployment?
- [ ] Passing any exploratory testing?
- [ ] Rebased/merged with latest changes from development and re-tested?
- [ ] Meeting the Coding Standards?

2024-06-05 14:47 UTC, balpurewal requested changes

2024-06-05 14:47 UTC, balpurewal commented on aws/modules/infrastructure_modules/eks/variables.tf
> +variable "trusted_key_identities" {
Don't believe this is needed

2024-06-05 17:05 UTC, dibyadhar commented on aws/modules/infrastructure_modules/eks/variables.tf
> +variable "trusted_key_identities" {
Yes thanks, removed now.

2024-06-11 16:40 UTC, closed without merging

2024-06-11 16:40 UTC, dibyadhar commented
This has been reviewed and added via separate PR